# Generated by Django 5.1 on 2024-10-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateTimeField()),
                ('transaction_message', models.CharField(max_length=1000)),
                ('location_location_of_the_transaction', models.CharField(max_length=200)),
                ('location_description', models.CharField(max_length=200)),
                ('category_of_the_transaction', models.CharField(max_length=50)),
                ('description_of_the_transaction', models.TextField()),
                ('ammount', models.IntegerField(default=0)),
                ('description_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_cost', models.IntegerField(default=0)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlogger.transaction')),
            ],
        ),
    ]
