# Generated by Django 5.1 on 2024-10-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description_name',
            new_name='name_of_recipients',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(default='paid', max_length=20),
            preserve_default=False,
        ),
    ]
