# Generated by Django 5.1 on 2024-10-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0003_transaction_transaction_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='location_location_of_the_transaction',
            new_name='geolocation_of_the_transaction',
        ),
    ]
