# Generated by Django 5.1 on 2024-10-27 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0005_rename_ammount_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_mpesa_msg_modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_of_mpesa_msg_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(choices=[('paid', 'Paid'), ('received', 'Received'), ('sent', 'Sent')], max_length=20),
        ),
    ]
