# Generated by Django 5.1 on 2024-10-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0006_transaction_date_of_mpesa_msg_modify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateField(),
        ),
    ]
