# Generated by Django 5.1 on 2024-10-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0007_alter_transaction_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateTimeField(),
        ),
    ]
