# Generated by Django 5.1 on 2024-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0008_alter_transaction_date_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(max_length=20),
        ),
    ]
