# Generated by Django 5.1 on 2024-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0009_alter_transaction_type_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(choices=[('paid', 'Paid'), ('received', 'Received'), ('sent', 'Sent')], max_length=20),
        ),
    ]
