# Generated by Django 5.1 on 2024-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0012_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_cost',
            field=models.FloatField(default=0),
        ),
    ]
