# Generated by Django 5.1.4 on 2024-12-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlogger', '0013_alter_transaction_transaction_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_transaction',
            field=models.CharField(max_length=200),
        ),
    ]
