# Generated by Django 5.1.4 on 2025-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='others', max_length=200),
            preserve_default=False,
        ),
    ]
