# Generated by Django 5.1.4 on 2025-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
