# Generated by Django 5.1.4 on 2025-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0003_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
