# Generated by Django 5.1.4 on 2025-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0004_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
