# Generated by Django 5.1.4 on 2025-04-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0005_service_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_batch_number', models.CharField(max_length=50)),
                ('stock_date', models.DateField()),
                ('stock_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('printing', 'Printing'), ('photocopy', 'Photocopy'), ('scanning', 'Scanning'), ('kra', 'KRA'), ('SHA / SHIF', 'SHA/SHIF'), ('emails', 'mail services'), ('browsing', 'Browsing'), ('passports', 'Passport Photo'), ('ntsa', 'NTSA'), ('HELB', 'HELB'), ('Sale', 'Sales'), ('lamination', 'Lamination'), ('typsetting', 'Typesetting'), ('songs', 'Songs'), ('tse', 'TSE'), ('mpesa statements', 'M-pesa statements'), ('pension', 'Pension'), ('others', 'others')], max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_retail_price', models.IntegerField(default=0)),
                ('product_wholesale_price', models.IntegerField(default=0)),
                ('product_category', models.CharField(choices=[('computing', 'computing'), ('Storage', 'Storage')], max_length=50)),
                ('product_description', models.CharField(max_length=200)),
                ('stock_batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyber.stock')),
            ],
        ),
    ]
