# Generated by Django 5.1.4 on 2025-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0007_product_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_message', models.CharField(max_length=200)),
                ('payment_message_upload_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='mode_of_payment',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('KCB', 'KCB')], default='KCB', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('computing', 'computing'), ('Storage', 'Storage'), ('charging', 'charging'), ('desktops', 'desktops'), ('laptops', 'laptops'), ('data cables', 'data cables')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('printing', 'Printing'), ('photocopy', 'Photocopy'), ('scanning', 'Scanning'), ('kra', 'KRA'), ('SHA / SHIF', 'SHA/SHIF'), ('emails', 'mail services'), ('browsing', 'Browsing'), ('passports', 'Passport Photo'), ('ntsa', 'NTSA'), ('HELB', 'HELB'), ('Sale', 'Sales'), ('lamination', 'Lamination'), ('typsetting', 'Typesetting'), ('songs', 'Songs'), ('tse', 'TSE'), ('mpesa statements', 'M-pesa statements'), ('pension', 'Pension'), ('others', 'others'), ('E-Citizen', 'E-Citizen'), ('Ghris', 'Ghris')], max_length=100),
        ),
    ]
