# Generated by Django 5.1.4 on 2025-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0009_mobile_banking_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile_banking_messages',
            name='mobile_bank_message_upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
